default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123QWEasd

development:
  database: DoAn_development
  <<: *default

test:
  database: DoAn_test
  <<: *default
  
production:
  database: DoAn_production
  <<: *default